declare -a misuses=(
"misuse1"
	"misuse2" 
	"misuse3"
"misuse4"
"misuse5"
#"misuse6"
"misuse7"
"misuse8"
"misuse9"
#"misuse10"
"misuse11"
"misuse12"
"misuse13"
"misuse14"
"misuse15"
"misuse16"
"misuse17"
"misuse18"
#"misuse19"
"misuse20"
"misuse21"
"misuse22"
"misuse23"
"misuse24"
#"misuse25"
"misuse26"
"misuse27"
"misuse28"
"misuse29"
#"misuse30"
"misuse31"
"misuse32"
"misuse33"
"misuse34"
"misuse35"
"misuse36"
"misuse37"
#"misuse38"
"misuse39"
"misuse40"
"misuse41"
"misuse42"
"misuse43"
"misuse44"
"misuse45"
"misuse46"
"misuse47"
"misuse48"
"misuse49"
"misuse50"
"misuse51"
"misuse52"
#"misuse53"
#"misuse54"
#"misuse55"
"misuse56"
"misuse57"
"misuse58"
"misuse59"
"misuse60"
"misuse61"
"misuse62"
"misuse63"
"misuse64"
"misuse65"
"misuse66"
"misuse67"
"misuse68"
"misuse69"
"misuse70"
"misuse71"
"misuse72"
#"misuse73"
"misuse74"
"misuse75"
"misuse76"
"misuse77"
"misuse78"
"misuse79"
"misuse80"
"misuse81"
"misuse82"
"misuse83"
"misuse84"
"misuse85"
"misuse86"
"misuse87"
"misuse88"
"misuse89"
"misuse90"
"misuse91"
"misuse92"
"misuse93"
"misuse94"
"misuse95"
"misuse96"
)

declare -a allofem=(
"org/cryptoapi/bench/staticsalts/StaticSaltsABHCase1"
	"org/cryptoapi/bench/brokencrypto/BrokenCryptoBBCase3"
	"org/cryptoapi/bench/staticinitializationvector/StaticInitializationVectorABHCase2"
"org/cryptoapi/bench/brokencrypto/BrokenCryptoABMC1"
"org/cryptoapi/bench/predictablecryptographickey/PredictableCryptographicKeyABHCase2" #5
#"org/cryptoapi/bench/brokencrypto/BrokenCryptoABICase5"
"org/cryptoapi/bench/predictablekeystorepassword/PredictableKeyStorePasswordABHCase2"
"org/cryptoapi/bench/insecureasymmetriccrypto/InsecureAsymmetricCipherABMC1"
"org/cryptoapi/bench/insecureasymmetriccrypto/InsecureAsymmetricCipherBBCase1"
#"org/cryptoapi/bench/brokenhash/BrokenHashABICase6"#10
"org/cryptoapi/bench/brokencrypto/BrokenCryptoBBCase4"
"org/cryptoapi/bench/ecbcrypto/EcbInSymmCryptoABICase1"
"org/cryptoapi/bench/pbeiteration/LessThan1000IterationPBEABICase2"
"org/cryptoapi/bench/predictablepbepassword/PredictablePBEPasswordBBCase1"
"org/cryptoapi/bench/staticinitializationvector/StaticInitializationVectorBBCase1"
"org/cryptoapi/bench/brokencrypto/BrokenCryptoABMC4"
"org/cryptoapi/bench/brokencrypto/BrokenCryptoBBCase2"
"org/cryptoapi/bench/pbeiteration/LessThan1000IterationPBEBBCase1"
#"org/cryptoapi/bench/brokencrypto/BrokenCryptoABICase6"
"org/cryptoapi/bench/predictablekeystorepassword/PredictableKeyStorePasswordBBCase1" #20
"org/cryptoapi/bench/brokenhash/BrokenHashABICase12"
"org/cryptoapi/bench/brokenhash/BrokenHashBBCase2"
"org/cryptoapi/bench/brokenhash/BrokenHashBBCase4"
"org/cryptoapi/bench/brokenhash/BrokenHashABICase4"
#"org/cryptoapi/bench/ecbcrypto/EcbInSymmCryptoABICase2"
"org/cryptoapi/bench/brokenhash/BrokenHashABMC2"
"org/cryptoapi/bench/brokenhash/BrokenHashABICase11"
"org/cryptoapi/bench/brokenhash/BrokenHashABMC3"
"org/cryptoapi/bench/brokencrypto/BrokenCryptoABMC2"
#"org/cryptoapi/bench/brokenhash/BrokenHashABICase8" #30
"org/cryptoapi/bench/brokencrypto/BrokenCryptoABICase4"
"org/cryptoapi/bench/brokenhash/BrokenHashABICase1"
"org/cryptoapi/bench/insecureasymmetriccrypto/InsecureAsymmetricCipherABICase1"
"org/cryptoapi/bench/brokencrypto/BrokenCryptoABICase12"
"org/cryptoapi/bench/insecureasymmetriccrypto/InsecureAsymmetricCipherABICase2"
"org/cryptoapi/bench/staticinitializationvector/StaticInitializationVectorABHCase1"
"org/cryptoapi/bench/brokencrypto/BrokenCryptoABICase15"
#"org/cryptoapi/bench/brokenhash/BrokenHashABICase5"
"org/cryptoapi/bench/brokencrypto/BrokenCryptoABICase9"
"org/cryptoapi/bench/predictablepbepassword/PredictablePBEPasswordBBCase2" #40
"org/cryptoapi/bench/brokencrypto/BrokenCryptoBBCase5"
"org/cryptoapi/bench/brokencrypto/BrokenCryptoABICase1"
"org/cryptoapi/bench/predictablepbepassword/PredictablePBEPasswordABMC1"
"org/cryptoapi/bench/staticinitializationvector/StaticInitializationVectorABICase1"
"org/cryptoapi/bench/predictablepbepassword/PredictablePBEPasswordABICase1"
"org/cryptoapi/bench/brokencrypto/BrokenCryptoABICase13"
"org/cryptoapi/bench/staticinitializationvector/StaticInitializationVectorABMC1"
"org/cryptoapi/bench/ecbcrypto/EcbInSymmCryptoABICase3"
"org/cryptoapi/bench/predictablecryptographickey/PredictableCryptographicKeyABICase1"
"org/cryptoapi/bench/pbeiteration/LessThan1000IterationPBEABICase1" #50
"org/cryptoapi/bench/predictablekeystorepassword/PredictableKeyStorePasswordABMC1"
"org/cryptoapi/bench/predictablekeystorepassword/PredictableKeyStorePasswordABICase3"
#"org/cryptoapi/bench/brokencrypto/BrokenCryptoABICase8"
#"org/cryptoapi/bench/brokencrypto/BrokenCryptoABICase7"
#"org/cryptoapi/bench/brokenhash/BrokenHashABICase7"
"org/cryptoapi/bench/staticsalts/StaticSaltsABICase1"
"org/cryptoapi/bench/ecbcrypto/EcbInSymmCryptoABMC1"
"org/cryptoapi/bench/staticinitializationvector/StaticInitializationVectorABICase2"
"org/cryptoapi/bench/pbeiteration/LessThan1000IterationPBEABICase3"
"org/cryptoapi/bench/brokenhash/BrokenHashABMC1" # 60
"org/cryptoapi/bench/brokencrypto/BrokenCryptoABICase2"
"org/cryptoapi/bench/brokenhash/BrokenHashBBCase1"
"org/cryptoapi/bench/staticsalts/StaticSaltsABMC1"
"org/cryptoapi/bench/staticinitializationvector/StaticInitializationVectorABICase3"
"org/cryptoapi/bench/pbeiteration/LessThan1000IterationPBEABMC1"
"org/cryptoapi/bench/ecbcrypto/EcbInSymmCryptoBBCase1"
"org/cryptoapi/bench/predictablepbepassword/PredictablePBEPasswordABMCCase1"
"org/cryptoapi/bench/staticsalts/StaticSaltsABICase3"
"org/cryptoapi/bench/brokencrypto/BrokenCryptoABICase14"
"org/cryptoapi/bench/brokencrypto/BrokenCryptoABMC3" #70
"org/cryptoapi/bench/brokencrypto/BrokenCryptoABMC5"
"org/cryptoapi/bench/staticsalts/StaticSaltsABICase2"
#"org/cryptoapi/bench/brokencrypto/BrokenCryptoABICase10"
"org/cryptoapi/bench/brokenhash/BrokenHashABICase9"
"org/cryptoapi/bench/staticsalts/StaticSaltsBBCase1"
"org/cryptoapi/bench/predictablecryptographickey/PredictableCryptographicKeyABMC1"
"org/cryptoapi/bench/predictablepbepassword/PredictablePBEPasswordABICase2"
"org/cryptoapi/bench/predictablepbepassword/PredictablePBEPasswordABSCase1"
	"org/cryptoapi/bench/brokencrypto/BrokenCryptoABICase3" 
"org/cryptoapi/bench/predictablepbepassword/PredictablePBEPasswordABICase3" #  80
"org/cryptoapi/bench/brokenhash/BrokenHashABICase2"
"org/cryptoapi/bench/insecureasymmetriccrypto/InsecureAsymmetricCipherABICase3"
"org/cryptoapi/bench/predictablecryptographickey/PredictableCryptographicKeyBBCase1"
"org/cryptoapi/bench/brokencrypto/BrokenCryptoBBCase1" #84
"org/cryptoapi/bench/predictablecryptographickey/PredictableCryptographicKeyABSCase1" #85
"org/cryptoapi/bench/brokenhash/BrokenHashABICase3"
"org/cryptoapi/bench/predictablecryptographickey/PredictableCryptographicKeyABHCase1"
"org/cryptoapi/bench/brokenhash/BrokenHashBBCase3" 
"org/cryptoapi/bench/brokencrypto/BrokenCryptoABICase11" #89
"org/cryptoapi/bench/predictablekeystorepassword/PredictableKeyStorePasswordABICase1"
"org/cryptoapi/bench/predictablekeystorepassword/PredictableKeyStorePasswordABICase2"
"org/cryptoapi/bench/predictablecryptographickey/PredictableCryptographicKeyABICase2"
"org/cryptoapi/bench/predictablecryptographickey/PredictableCryptographicKeyABICase3"
"org/cryptoapi/bench/predictablepbepassword/PredictablePBEPasswordABHCase2"
"org/cryptoapi/bench/brokenhash/BrokenHashABICase10" 
"org/cryptoapi/bench/brokenhash/BrokenHashABMC4" #96

	)
for index in "${!allofem[@]}"
do

	#FOR OGS
#	ls /root/eval/cryptoapi-bench/build/classes/java/main//${allofem[index]}.class
#	cp /root/eval/cryptoapi-bench/src/main/java/${allofem[index]}.java /root/crypto-bench-patched/src/main/java/

	#FOR patches
#	cp /root/eval/cryptoapi-bench/patch/${misuses[index]}/${allofem[index]}.java /root/crypto-bench-patched/src/main/java/${allofem[index]}.java


	#for adapter outs
	var="$(echo ${allofem[index]} | cut -d / -f -4)"
	echo "copying: "
	find /root/eval/successCryptoGuard/${misuses[index]}/adapterOutputs -name "*.class"
	echo "into: /root/cryptoadapterOuts/build/classes/java/main/$var"
	find /root/eval/successCryptoGuard/${misuses[index]}/adapterOutputs -name "*.class" -exec cp "{}" /root/eval/cryptoadapterOuts/build/classes/java/main/$var \;
	
	done
